from .evolink_gpt_image2 import NODE_CLASS_MAPPINGS as GPT_NODE_CLASS_MAPPINGS
from .evolink_gpt_image2 import NODE_DISPLAY_NAME_MAPPINGS as GPT_NODE_DISPLAY_NAME_MAPPINGS
from .evolink_image_input import NODE_CLASS_MAPPINGS as IMAGE_INPUT_NODE_CLASS_MAPPINGS
from .evolink_image_input import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_INPUT_NODE_DISPLAY_NAME_MAPPINGS

# Merge all node mappings
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(GPT_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(IMAGE_INPUT_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(GPT_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(IMAGE_INPUT_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
